### ISSUE TITLE
Feat:  Add loading Indicator

### ISSUE THREAD

**Issue by seanvree** [seanvree/logarr#20]
Need some type of "loading" indicator. Something simple like Organizr uses.

**Comment by seanvree** [comment]
Example:

http://jsfiddle.net/onigetoc/75LJ8/

https://jsfiddle.net/MrPolywhirl/cbLsc81f/

**Comment by seanvree** [comment]
Dis one:

http://talkerscode.com/webtricks/display-progress-bar-while-page-loads-using-jquery.php

**Comment by seanvree** [comment]
Added to Develop

https://github.com/seanvree/logarr/commit/d94937f7d03c3e92eef01332f90c317331d51b5a

**Comment by jonfinley** [comment]
pushed to master.
