### ISSUE TITLE
BUG: HTML in Log Files Breaks Site

### ISSUE THREAD

**Issue by kmlucy** [seanvree/logarr#25]
My log files for Jackett contain html, and specifically the problem is that they contain magnet links. EX:

```
System.Exception: Error while parsing field=download, selector=td > a[href^="/file"], value=<null>: Selector "td > a[href^="/file"]" didn't match <tr>   <td style="word-wrap: break-word;"> <a href="***" title="***">***</a>       <img alt="Verified" title="Verified and marked" src="/images/verified.png" width="20" height="20">                         <br>             <a href="magnet:?xt=urn:***" rel="nofollow"> <img alt="Download *** using magnet link" title="Download *** using magnet link" src="/images/magnet.svg" width="16" height="16">
                </a>  Uploaded 2 days ago Size 1.9 GB</td>
        <td class="is-hidden-touch">1.9 GB</td>
        <td class="is-hidden-touch" style="text-align: center;">6</td> <td class="is-hidden-touch" style="text-align: center;">2 days ago</td>
        <td style="text-align: center;">1492</td>
        <td style="text-align: center;">1110</td>
</tr>
```

Because of this, everything below this log file functions as the embedded link. There needs to be some way to negate any html that happens to be in the log files.

**Comment by kmlucy** [comment]
Sorry, just realized this is a duplicate of #8 .

**Comment by seanvree** [comment]
@kmlucy  - 

Yeah, I can't figure out why this does this.  I know it's the markup in the actual log files.  There MAY be no way around it.  But yeah, what I've been doing is putting the offending logging application at the end of my list then when it rolls over, it obv fixes itself.
