### ISSUE TITLE
BUG:  Only first DIV Collapsable tables function correctly.

### ISSUE THREAD

**Issue by seanvree** [seanvree/logarr#3]
Feature: Collapsible tables

Some way to collapse tables so data from all logs isn't loaded initially.

**Comment by leram84** [comment]
would be good to have 3 states instead of two: collapsed, expanded, and LARGE... so u can blow up a window full page if your working on a specific log and need more room to work

**Comment by seanvree** [comment]
@leram84  whoa buddy, sheesh.

Ha, JK, Yeah, for starters, I was just thinking something simple  - so the default page would show each "logger" and then a simple link or "activate" button or something that would then show the table. ... 

But yeah, we on the same page. SO GET TO WORK!

**Comment by jonfinley** [comment]
I'm thinking something like this: http://jsfiddle.net/ThinkingStiff/NXB2g/

**Comment by seanvree** [comment]
DUDE! YES!

**Comment by seanvree** [comment]
@jonfinley  I did it!

Incoming!

**Comment by jonfinley** [comment]
So doing research, because I don't really remember my JS classes. Every Id needs to be unique in the fact that we basically need a `more1` `more2` `more3` for every single time it generates per log.

see this link, bottom comment: https://stackoverflow.com/questions/29630109/jquery-affect-all-instances-of-a-table-id

**Comment by seanvree** [comment]
@jonfinley okay, yeah, I understand the issue.  I just have NO IDEA how to implement that into the magic that @Causefx dropped on us.  

I tested the code ref below and it works, but you have to have separate DIV IDs for each logger...I"m assuming there's away to assign a class to each DIV automatically?  Way over my head. 


https://api.jquery.com/addclass/

**Comment by jonfinley** [comment]
commited: https://github.com/seanvree/logarr/commit/0394cf384ed467d08cb9944c0ee4bb8cf65a0058
