### ISSUE TITLE
FEAT: Normalize time stamps

### ISSUE THREAD

**Issue by leram84** [seanvree/logarr#34]
set a standard format for date/time so you're not stuck with the default log format. 

... then create a settings gui just so the Europeans can change it to whatever nonsense they want :)

**Comment by seanvree** [comment]
@leram84 

Unfortunately, this isn't possible.  With the way Logarr is designed, it does not edit the actual log data.  You'd have to somehow edit the DTG format within the logging application it'self. 

The settings page is on the way!
