### ISSUE TITLE
[Issue] Logarr not pulling Nzbhydra logs

### ISSUE THREAD

**Issue by elmerfdz** [seanvree/logarr#4]
![image](https://user-images.githubusercontent.com/22656503/28747829-071e94b6-74a0-11e7-8d2c-f65ffd484277.png)

**Comment by seanvree** [comment]
@elmerfdz  - 

I can't reproduce on my machine. it's working for me. 

![image](https://user-images.githubusercontent.com/8906637/28747952-08ac4a70-7460-11e7-98a2-88b854f09e24.png)


What OS are you using?

Try replacing  the < ""> with < ' '>

example:

```
 $filename     = "C:\nzbhydra\nzbhydra.log";
```
 to 

```
 $filename     = 'C:\nzbhydra\nzbhydra.log';
``

**Comment by seanvree** [comment]
also, check PERMISSIONS.

**Comment by seanvree** [comment]
@elmerfdz   - it's a permissions issue buddy.

**Comment by elmerfdz** [comment]
thanks for looking into this, it needed the single quotes on Windows, On Ubuntu "C:\nzbhydra\nzbhydra.log" or  'C:\nzbhydra\nzbhydra.log' either works
