### ISSUE TITLE
BUG:  Sonarr cloudflair

### ISSUE THREAD

**Issue by seanvree** [seanvree/logarr#40]
Not sure what's causing this, but Sonarr logs are causing a cloudflair issue:
![inkedlogarrsonarr_li](https://user-images.githubusercontent.com/8906637/30723127-15d7b5ae-9eea-11e7-997c-037d24f78fc0.jpg)

**Comment by saitoh183** [comment]
same here

**Comment by jonfinley** [comment]
same.

**Comment by saitoh183** [comment]
Seems clearing the Radarr and sonarr logs stops the problem

**Comment by seanvree** [comment]
@saitoh183  yeah, I'll close this for now.
