### ISSUE TITLE
FEAT: Search function

### ISSUE THREAD

**Issue by seanvree** [seanvree/logarr#7]
To DO:

 - Add # of results from search output below search box
- "ENTER" key to search?
- How to clear search result highlighting w/o refreshing the page

**Comment by seanvree** [comment]
Initial Search function added. However, it is NOT searching the collapsable DIVs

REF:

https://osvaldas.info/real-time-search-in-javascript

**Comment by seanvree** [comment]
after several days of emotional strife.  

Essentially our search function needs to work EXACTLY like "CTRL F" does in Chrome and MOST modern browsers.  Need it to simply highlight all results of input text.

**Comment by seanvree** [comment]
initial fix committed to develop https://github.com/seanvree/logarr/commit/422acb608e482655dae2d76f93b1f19ddb239a77

**Comment by jonfinley** [comment]
pushed to master.
